version: '3.7'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    image: macbookbro
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: >
      gunicorn -w 4 -b 0.0.0.0:8080 app:app
    restart: always

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: always
